# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
        ('ItemManager', '0002_auto_20170920_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemManager.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.customer')),
            ],
        ),
    ]
